### ISSUE TITLE
Why is there so much HTML code in your .go files?

### ISSUE THREAD

**Issue by xPushkin** [Eggbertx/gochan#1]
It would be much better if you created a stable REST API for the imageboard.

Firstly, it doesn't help caching if you keep sending same HTML from the server over and over again.
Secondly, you are limiting yourself to browser viewing only, so no phone app.
Lastly, it just looks like spaghetti code.

**Comment by Eggbertx** [comment]
1. An API that will likely be relatively similar to 4chan's is currently in the works, and will serve static JSON files which will only be modified/created with new/removed threads/posts/boards.
2. As for the phone apps, see the above, though we do have plans to tune the UI to be phone friendly, without being a drain on JavaScript. I loathe sites whose mobile version is takes longer to load than the desktop version.
3. As for spaghetti code, that is being worked on as well. You're more than welcome to make changes and pull requests.
