### ISSUE TITLE
Use gometalinter

### ISSUE THREAD

**Issue by pqyptixa** [Eggbertx/gochan#13]
Please use gometalinter (https://github.com/alecthomas/gometalinter), which is a tool that
>  Concurrently run Go lint tools and normalise their output

I ran it againt the gochan code and got:
```
$ gometalinter --deadline 900s | wc -l
431
```
Using it is easy (as explained in https://github.com/alecthomas/gometalinter#installing and https://github.com/alecthomas/gometalinter#quickstart):
```
$ go get -u github.com/alecthomas/gometalinter
$ gometalinter --install
$ cd /path/to/src
$ gometalinter
```
Most of the warnings are formatting warnings, but some could point to serious bugs:

> manage.go:83:: warning: SQL string concatenation,MEDIUM,HIGH (gas)
manage.go:93:: warning: SQL string concatenation,MEDIUM,HIGH (gas)
manage.go:141:: warning: SQL string concatenation,MEDIUM,HIGH (gas)
manage.go:146:: warning: SQL string concatenation,MEDIUM,HIGH (gas)
manage.go:162:: warning: SQL string concatenation,MEDIUM,HIGH (gas)
manage.go:225:: warning: SQL string concatenation,MEDIUM,HIGH (gas)
manage.go:339:: warning: SQL string concatenation,MEDIUM,HIGH (gas)
manage.go:389:: warning: SQL string concatenation,MEDIUM,HIGH (gas)
manage.go:441:: warning: SQL string concatenation,MEDIUM,HIGH (gas)
manage.go:492:: warning: SQL string concatenation,MEDIUM,HIGH (gas)
manage.go:586:: warning: Expect directory permissions to be 0700 or less,MEDIUM,HIGH (gas)
manage.go:592:: warning: Expect directory permissions to be 0700 or less,MEDIUM,HIGH (gas)
manage.go:598:: warning: Expect directory permissions to be 0700 or less,MEDIUM,HIGH (gas)
manage.go:604:: warning: Expect directory permissions to be 0700 or less,MEDIUM,HIGH (gas)
manage.go:610:: warning: SQL string concatenation,MEDIUM,HIGH (gas)
manage.go:653:: warning: SQL string concatenation,MEDIUM,HIGH (gas)
manage.go:718:: warning: SQL string concatenation,MEDIUM,HIGH (gas)
manage.go:737:: warning: SQL string concatenation,MEDIUM,HIGH (gas)
manage.go:816:: warning: SQL string concatenation,MEDIUM,HIGH (gas)
manage.go:839:: warning: SQL string concatenation,MEDIUM,HIGH (gas)
manage.go:887:: warning: SQL string concatenation,MEDIUM,HIGH (gas)
manage.go:906:: warning: SQL string concatenation,MEDIUM,HIGH (gas)
manage.go:917:: warning: SQL string concatenation,MEDIUM,HIGH (gas)
posting.go:7:: warning: Use of weak cryptographic primitive,HIGH,HIGH (gas)
posting.go:88:: warning: Expect directory permissions to be 0700 or less,MEDIUM,HIGH (gas)
posting.go:118:: warning: SQL string concatenation,MEDIUM,HIGH (gas)
posting.go:129:: warning: SQL string concatenation,MEDIUM,HIGH (gas)
posting.go:197:: warning: Expect file permissions to be 0600 or less,MEDIUM,HIGH (gas)
posting.go:227:: warning: Expect file permissions to be 0600 or less,MEDIUM,HIGH (gas)
posting.go:239:: warning: Expect file permissions to be 0600 or less,MEDIUM,HIGH (gas)
posting.go:379:: warning: Expect file permissions to be 0600 or less,MEDIUM,HIGH (gas)
posting.go:398:: warning: Expect file permissions to be 0600 or less,MEDIUM,HIGH (gas)
posting.go:435:: warning: Expect file permissions to be 0600 or less,MEDIUM,HIGH (gas)
posting.go:466:: warning: Expect file permissions to be 0600 or less,MEDIUM,HIGH (gas)
posting.go:473:: warning: SQL string concatenation,MEDIUM,HIGH (gas)
posting.go:491:: warning: SQL string concatenation,MEDIUM,HIGH (gas)
posting.go:531:: warning: Expect file permissions to be 0600 or less,MEDIUM,HIGH (gas)
posting.go:566:: warning: SQL string concatenation,MEDIUM,HIGH (gas)
posting.go:584:: warning: SQL string concatenation,MEDIUM,HIGH (gas)
posting.go:627:: warning: SQL string concatenation,MEDIUM,HIGH (gas)
posting.go:663:: warning: Subprocess launching with variable.,HIGH,HIGH (gas)
posting.go:677:: warning: Subprocess launching with variable.,HIGH,HIGH (gas)
posting.go:736:: warning: SQL string concatenation,MEDIUM,HIGH (gas)
posting.go:828:: warning: SQL string concatenation,MEDIUM,HIGH (gas)
posting.go:925:: warning: Use of weak cryptographic primitive,MEDIUM,HIGH (gas)
posting.go:928:: warning: SQL string concatenation,MEDIUM,HIGH (gas)
posting.go:967:: warning: Subprocess launching with variable.,HIGH,HIGH (gas)
posting.go:1149:: warning: SQL string concatenation,MEDIUM,HIGH (gas)
server.go:216:: warning: SQL string concatenation,MEDIUM,HIGH (gas)
server.go:254:: warning: SQL string concatenation,MEDIUM,HIGH (gas)
server.go:272:: warning: SQL string concatenation,MEDIUM,HIGH (gas)
server.go:296:: warning: SQL string concatenation,MEDIUM,HIGH (gas)
server.go:313:: warning: SQL string concatenation,MEDIUM,HIGH (gas)
server.go:322:: warning: SQL string concatenation,MEDIUM,HIGH (gas)
server.go:330:: warning: SQL string concatenation,MEDIUM,HIGH (gas)
server.go:337:: warning: SQL string concatenation,MEDIUM,HIGH (gas)
sql.go:36:: warning: SQL string concatenation,MEDIUM,HIGH (gas)
sql.go:69:: warning: SQL string concatenation,MEDIUM,HIGH (gas)
sql.go:112:: warning: SQL string formatting,MEDIUM,HIGH (gas)
types.go:472:: warning: Expect file permissions to be 0600 or less,MEDIUM,HIGH (gas)
types.go:481:: warning: Expect file permissions to be 0600 or less,MEDIUM,HIGH (gas)
types.go:489:: warning: Expect file permissions to be 0600 or less,MEDIUM,HIGH (gas)
util.go:5:: warning: Use of weak cryptographic primitive,HIGH,HIGH (gas)
util.go:49:: warning: Use of weak cryptographic primitive,MEDIUM,HIGH (gas)
util.go:168:: warning: SQL string concatenation,MEDIUM,HIGH (gas)
util.go:264:: warning: SQL string concatenation,MEDIUM,HIGH (gas)
util.go:323:: warning: SQL string concatenation,MEDIUM,HIGH (gas)

**Comment by Eggbertx** [comment]
I have it set up to (for the most part) keep your development environment separate from the VM so this isn't really something to add to the repo, but this definitely seems pretty useful. Thanks for the tip!
