### ISSUE TITLE
Question regarding this project

### ISSUE THREAD

**Issue by DonaldTsang** [Eggbertx/gochan#14]
How is this project different from https://github.com/bakape/meguca since both are written in Go?

**Comment by onekopaka** [comment]
gochan is a very traditional style imageboard, that generates static HTML pages that can be served by a web server. meguca seems to have WebSockets to connect clients to the server so they get posts pushed in realtime.

**Comment by DonaldTsang** [comment]
Is it possible to add this explanation to the ReadME? Would be useful to detail thegoals of the project.

**Comment by onekopaka** [comment]
I've updated the README in commit 1cd3fc2c409c5aac388d7cdd8537b7c08a690072. Let me know if that change clears things up.

**Comment by onekopaka** [comment]
Due to it being over a week since the last comment from the reporter, and I've added an explanation that gochan generates static HTML to the README file, I'm closing this issue. If there are further questions, it can be reopened.

**Comment by DonaldTsang** [comment]
@onekopaka originally I would like to ask for a "product comparison" table but that is too much to ask for, I would assume. Good to close it anyway.
