### ISSUE TITLE
Can't login after a fresh install

### ISSUE THREAD

**Issue by misaka00251** [Eggbertx/gochan#17]
So I already know the default username and password:
![image](https://user-images.githubusercontent.com/3908746/74085472-31e6cf00-4ab4-11ea-837d-2f31c9c3a71a.png)

But it won't log in...

![image](https://user-images.githubusercontent.com/3908746/74085477-3ca16400-4ab4-11ea-9324-5ef0ab02f7f2.png)

No error output in browser console.

Gochan log:

```
Feb 08 20:36:34 systemd[1]: Started gochan Daemon.
Feb 08 20:36:35 gochan[10263]: Starting gochan v2.11.2., using verbosity level 1
Feb 08 20:36:35 gochan[10263]: Initializing server...
Feb 08 20:36:35 gochan[10263]: This looks like a new installation. Creating /test/ and a new staff member.
Feb 08 20:36:35 gochan[10263]: Username: admin
Feb 08 20:36:35 gochan[10263]: Password: password
Feb 08 20:36:35 gochan[10263]: Failed creating /test/ with error: [ERROR] src/gochan.go:27: Error 1364: Field 'default_style' doesn't have a default value
Feb 08 20:36:35 gochan[10263]: Loading and parsing templates...
Feb 08 20:36:35 gochan[10263]: Built gochan.min.js and consts.js successfully.
```

**Comment by misaka00251** [comment]
Well, I enabled Mariadb's general query log, and I can't see anything when I'm login.

**Comment by onekopaka** [comment]
Check the mod log (it's a seperate file) for entries like "Rejected login from possible spambot"

If you see that, the problem is that you need to set your DomainRegex in your configuration file so that the "Referer" (HTTP does spell it that way lol) header is matches it.

**Comment by misaka00251** [comment]
Ah, I need to disable `add_header Referrer-Policy no-referrer`.
